workflows:
  android-workflow:
    name: Android APK Build

    environment:
      flutter: stable
      java: 17

    scripts:
      - name: Install Dependencies
        script: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flet-cli

      - name: Build APK
        script: |
          flet build apk --org com.anorin --project anorintool --yes --verbose

    artifacts:
      - build/**/outputs/**/*.apk